name: Generate xml sitemap

on:
  push:
    branches: [ gh-pages ]
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
        ref: gh-pages

    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://goka.dev/

    - name: Push the sitemap to gh-pages
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        title: "Automated sitemap update"
        commit_message: Sitemap updated by the generate-sitemap GitHub action.
        branch: gh-pages
        file_pattern: '*.xml'
